version: 0.2

phases:
  install:
    commands:
      - echo "Setting up Docker"
      - sudo yum install -y docker  
      - sudo systemctl start docker
      - sudo systemctl enable docker
      - echo "Running Nginx container"
      - sudo docker run -d -p 80:80 --name nginx-container nginx
  build:
    commands:
      - echo "Build phase started"
      - sudo cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo "Container started with Nginx"
      - sudo docker ps

artifacts:
  files:
    - usr/share/nginx/html/index.html
