version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx"
      - sudo yum update -y
      - sudo yum install -y nginx
  build:
    commands:
      - echo "Build start"
      - sudo cp index.html /usr/share/nginx/html
  post_build:
    commands:
      - echo "Configuring Nginx server"
      - sudo systemctl start nginx
      - sudo systemctl enable nginx

artifacts:
  files:
    - usr/share/nginx/html/index.html
